name: Build and Deploy

on: workflow_dispatch

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set image tag from Git SHA
        id: set-tag
        run: echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t prashant6749/myntra:${{ steps.set-tag.outputs.image_tag }} .
          docker push prashant6749/myntra:${{ steps.set-tag.outputs.image_tag }}

  