name: Build and Push to ECR (hardcoded)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin 234299494388.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: |
          IMAGE_URI=234299494388.dkr.ecr.ap-south-1.amazonaws.com/b11:${{ github.sha }}
          docker build -t $IMAGE_URI .

      - name: Push image to Amazon ECR recheck
        run: |
          IMAGE_URI=234299494388.dkr.ecr.ap-south-1.amazonaws.com/b11:${{ github.sha }}
          docker push $IMAGE_URI

      - name: Verify image in ECR
        run: |
          echo "Checking if image exists in ECR..."
          aws ecr describe-images \
            --repository-name b11 \
            --image-ids imageTag=${{ github.sha }} \
            --region ap-south-1 \
          && echo "✅ Image exists in ECR" \
          || (echo "❌ Image not found in ECR" && exit 1)
