name: Build and Deploy

on: workflow_dispatch

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set image tag from Git SHA
        id: set-tag
        run: echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Show image tag
        run: echo "Image will be pushed as prashant6749/b14:${{ steps.set-tag.outputs.image_tag }}"

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t prashant6749/b14:${{ steps.set-tag.outputs.image_tag }} .
          docker push prashant6749/b14:${{ steps.set-tag.outputs.image_tag }}
